apiVersion: batch/v1
kind: Job
metadata:
  generateName: after-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: [sh, -c, "sleep 10; exit 1"]
      restartPolicy: Never
  backoffLimit: 0
